//
//  PreviewData.swift
//  ANCHOR
//
//  Generated by generate_preview_data.py
//

import Foundation

struct PreviewData {
    static let shared = PreviewData()
    
    // MARK: - User Profile
    static let sampleUserProfile = UserProfileModel(
        id: UUID(),
        displayName: "Demo User",
        sobrietyStartDate: Calendar.current.date(byAdding: .day, value: -156, to: Date()) ?? Date(),
        createdAt: Date()
    )
    
    // MARK: - Journal Entries
    static let sampleJournalEntries: [JournalEntryModel] = [
        JournalEntryModel(
            id: UUID(),
            title: "Weekend Recovery",
            body: "Today I woke up feeling more optimistic than usual. I've been practicing the breathing exercises fro...",
            tags: ['Forgiveness', 'Healing'],
            createdAt: Date(),
            sentiment: "positive",
            sentimentScore: 0.39
        ),
        JournalEntryModel(
            id: UUID(),
            title: "Celebrating Small Wins",
            body: "Practiced mindfulness meditation for 15 minutes this morning. It's becoming easier to observe my tho...",
            tags: ['Reflection', 'Journey'],
            createdAt: Date(),
            sentiment: "neutral",
            sentimentScore: 0.77
        ),
        JournalEntryModel(
            id: UUID(),
            title: "Progress Check-in",
            body: "Had some cravings today but I used my coping strategies. Called a friend, went for a walk, and remin...",
            tags: ['Therapy', 'Growth'],
            createdAt: Date(),
            sentiment: "positive",
            sentimentScore: 0.25
        ),
        JournalEntryModel(
            id: UUID(),
            title: "Anxiety Management",
            body: "Practiced mindfulness meditation for 15 minutes this morning. It's becoming easier to observe my tho...",
            tags: ['Therapy', 'Growth'],
            createdAt: Date(),
            sentiment: "positive",
            sentimentScore: 0.29
        ),
        JournalEntryModel(
            id: UUID(),
            title: "Therapy Homework",
            body: "Feeling anxious about an upcoming presentation at work. Instead of catastrophizing, I'm trying to fo...",
            tags: ['Anxious', 'Work', 'Coping'],
            createdAt: Date(),
            sentiment: "negative",
            sentimentScore: 0.83
        )
    ]
    
    // MARK: - Risk Assessments
    static let sampleRiskAssessments: [RiskAssessmentModel] = [
        RiskAssessmentModel(
            id: UUID(),
            score: 5,
            reason: "Having trouble sleeping and feeling emotionally un...",
            createdAt: Date()
        ),
        RiskAssessmentModel(
            id: UUID(),
            score: 5,
            reason: "Feeling overwhelmed with work stress and family re...",
            createdAt: Date()
        ),
        RiskAssessmentModel(
            id: UUID(),
            score: 2,
            reason: "Having trouble sleeping and feeling emotionally un...",
            createdAt: Date()
        )
    ]
}

// MARK: - Preview Extensions
extension JournalEntryModel {
    static var preview: JournalEntryModel {
        PreviewData.sampleJournalEntries.first!
    }
}

extension RiskAssessmentModel {
    static var preview: RiskAssessmentModel {
        PreviewData.sampleRiskAssessments.first!
    }
}

extension UserProfileModel {
    static var preview: UserProfileModel {
        PreviewData.sampleUserProfile
    }
}
